package com.github.jacekolszak.aseprite;

public enum BlendMode {

    NORMAL, DARKEN, MULTIPLY, COLOR_BURN, LIGHTEN, SCREEN, COLOR_DODGE, ADDITION, OVERLAY, SOFT_LIGHT, HARD_LIGHT,
    DIFFERENCE, EXCLUSION, SUBTRACT, DIVIDE, HUE, SATURATION, COLOR, LUMINOSITY

}
